### ISSUE TITLE
Pokémon location on their page

### ISSUE THREAD

**Issue by FranciscoMoraC** [FredericDlugi/platinum-renegade-wiki#1]
I think that adding where to find each Pokémon could be useful. I used a couple of scripts to update the Pokémon pages, I'll attach the new pages.

[pokemon_changes.zip](https://github.com/FredericDlugi/platinum-renegade-wiki/files/8957209/pokemon_changes.zip)

**Comment by FredericDlugi** [comment]
This is a good Idea! Since I have adjusted the files since you made the changes I have implemented this on the current master myself. I should be live right now. Thanks for the idea! Hope you like the way I have done it.
